---
- hosts: all
  gather_facts: no
  remote_user: ansible
  tasks:
    - name: Test connection
      ping:
      remote_user: ansible
    - name: changing somthing
      copy:
      src: /etc/sudoers
      dest: /etc/sudoers.edit
      name: apache2
      state: present
   - name: Start Apache service
     service:
     name: apache2
      state: started
      enabled: true
...


