---
- hosts: all
  gather_facts: no
  remote_user: ansible
  tasks:
    - name: Test connection
      ping:
      remote_user: ansible
    - name: changing somthing
      copy:
        src: /opt
        dest: /etc
      ansible.builtin.apt:
        name: apache2
        state: present # Ensure the package is installed
...


